### ISSUE TITLE
Change sample text ability

### ISSUE THREAD

**Issue by manjav** [ctcuff/vscode-font-preview#1]
Please provide sample text in settings to change for other languages

**Comment by ctcuff** [comment]
> Please provide sample text in settings to change for other languages

Are there any specific languages you were thinking of?

**Comment by ctcuff** [comment]
Gonna close this since it was addressed in version 1.1.2 (c3b373624dde75fb388fc1c306260c256b21e327) but I'm always open to more suggestions!
