### ISSUE TITLE
How do I activate it or view it?

### ISSUE THREAD

**Issue by lundeen-bryan** [ctcuff/vscode-font-preview#14]
Sorry but I'm not seeing the same view as the preview. I pressed F1 which is my keybinding for looking at the command pallette. I typed "Font" and waited to see if "Font Preview" showed up but nothing. Then looked in the side bar for a tab showing "Font Preview" but didn't see anything. Went to the keyboard settings and typed "Font Preview" but no keybinding. Went to develper reload and reloaded the window but still can't find the extension. Shut down and restarted but still no preview. Can someone just explain how to see this extension? I uninstalled it and reinstalled it but still nothing. 

Expected: an entry in the command pallette called View Font Preview
Actual: nothing found called Font Preview in VS Code

**Comment by ctcuff** [comment]
Hey so once installed, the extension will be activated when you try to open a font file in the editor. Here's a screenshot for an example. Here, I have the inter font in my directory, and opening the file with the extension installed opens up the preview (currently I'm on the glyphs tab to view available characters/glyphs for the font)
 
![Figma - Screen Shot 2024-02-15 at 9 49 1](https://github.com/ctcuff/vscode-font-preview/assets/7400747/3f8ca24e-7cfa-4fd5-9da9-c53aab60a017)

Let me know if you have any other questions!
