### ISSUE TITLE
Feature Request: Preferred Tab

### ISSUE THREAD

**Issue by revilowaldow** [ctcuff/vscode-font-preview#2]
This is a feature request for a setting that I can change so that when previewing a font it always opens on my preferred tab. 
In my case, I would like it to always open on the "Glyphs" tab.

![image](https://user-images.githubusercontent.com/52298102/127753616-2371462a-5a1d-4880-8c53-e53cb9ad70a1.png)

This is a great extension, thank you!

**Comment by ctcuff** [comment]
Sure, this is a great suggestion!

**Comment by ctcuff** [comment]
This is officially a feature as of version 1.2.2 (fdb272ba076e47151b6823ff5ae9986f1ebe685e) 🎉. Let me know if you have any other issues!
