### ISSUE TITLE
can't load SourceHanSansSC

### ISSUE THREAD

**Issue by tjx666** [ctcuff/vscode-font-preview#3]
Always loading.

font file:
[SourceHanSansSC-Regular.otf.zip](https://github.com/ctcuff/vscode-font-preview/files/7387364/SourceHanSansSC-Regular.otf.zip)

**Comment by ctcuff** [comment]
The extension isn't the best at loading font files that large unfortunately but I've been working on trying to find a way around this though so stay tuned!

**Comment by ctcuff** [comment]
Closing this since it's finally fixed in v2.0.0 (49705d7080f0325dc3ae2666554e7bf8337b5125). You should be able to load the font in your editor now 👍
