### ISSUE TITLE
Get font assent, descent, Win/HHead ascent, Win/HHead descent info

### ISSUE THREAD

**Issue by tjx666** [ctcuff/vscode-font-preview#4]
![image](https://user-images.githubusercontent.com/41773861/138993925-410113d7-fb93-4f95-8801-89578ebcffba.png)

**Comment by ctcuff** [comment]
Closing since this was addressed in v2.0.0 (944887157e456d58951707cff727ac3776c2c8a2), you can view `ascent`, `descent`, and `baseline` information by clicking on a glyph in the `Glyph` tab. I plan on improving this feature in later versions so let me know if you have any further suggestions!
